# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ivan Bliskavka
subtitle: Digital Inventor
description: Notebook of tips, tricks and walkthroughs I create for personal reference. If you have questions feel free to reach out in the comments or social media.
keywords:
author: Ivan Bliskavka
language: en
timezone: America/New_York

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://bliskavka.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls.trailing_index: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hueman

theme_config:
  menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    # Categories:
    screen-saver-gallery: https://liandrasoftworks.com/Screen-Saver-Gallery
    about: /About
    contact: /Contact
  customize:
    theme_color: '#01a31c'
    thumbnail: false
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
      linkedin: https://www.linkedin.com/in/ibliskavka
      # facebook: https://www.facebook.com/ivan.bliskavka.5
      github: https://github.com/ibliskavka
      rss: /atom.xml
  search:
    insight: true
  comment:
    disqus: bliskavka
    facebook: true
  plugins:
    google_analytics: G-T2H8V95YZF
  miscellaneous:
    open_graph: # see http://ogp.me
      fb_app_id:
      fb_admins:
      twitter_id:
      google_plus:
    links:
      Screen Saver Gallery: https://apps.microsoft.com/detail/9nblggh5j8tx
      Liandra Softworks: https://www.liandrasoftworks.com
      Mind Wellness: https://mind-wellness.net

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# https://github.com/hexojs/hexo-generator-feed
feed:
  enable: true
  type:
    - atom
  path:
    - atom.xml
  limit: 0
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  autodiscovery: true
