AWSTemplateFormatVersion: 2010-09-09


Description: >
  Creates the bliskavka.com Environment

Parameters:

  Client:
    Type: String
    Default: bliskavka

  Project:
    Type: String
    Default: home

  Environment:
    Type: String
    Default: dev

  BaseUrl:
    Type: String
    Default: bliskavka.com
    Description : The DNS name of an existing Amazon Route 53 hosted zone,
    AllowedPattern : (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)[^\\.]$
    ConstraintDescription : Must be a valid DNS zone name WITHOUT trailing period.

  AppUrl:
    Type: String
    Default: www.bliskavka.com

  AcmCertArn:
    Type: String
    Default: arn:aws:acm:us-east-1:857240696749:certificate/4cabb1e7-2422-4f2d-b1cc-32c82378fff7

  MinTTL:
    Type: Number
    Default: 1800

  DefaultTTL:
    Type: Number
    Default: 3600

  MaxTTL:
    Type: Number
    Default: 86400

Resources:

#Start Web App Section

  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-app
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - RoutingRuleCondition:
              KeyPrefixEquals: piwigo/privacypolicy.html
            RedirectRule:
              HttpRedirectCode: 301
              HostName: !Sub ${BaseUrl}
              Protocol: https
              ReplaceKeyWith: Piwigo-Gallery-Privacy-Policy/index.html
          - RoutingRuleCondition:
              KeyPrefixEquals: NormalDayInRussia/privacypolicy.html
            RedirectRule:
              HttpRedirectCode: 301
              HostName: !Sub ${BaseUrl}
              Protocol: https
              ReplaceKeyWith: Normal-Day-In-Russia-Privacy-Policy/index.html
          - RoutingRuleCondition:
              KeyPrefixEquals: screensavergallery/privacy.html
            RedirectRule:
              HttpRedirectCode: 301
              HostName: !Sub ${BaseUrl}
              Protocol: https
              ReplaceKeyPrefixWith: Screen-Saver-Gallery-Privacy-Policy/index.html
      Tags:
        - Key: Client
          Value: !Ref Client
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  AppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: WebAppBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: "Grant a CloudFront Origin Identity access to support private content"
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "${AppBucket.Arn}/*"
      Bucket: !Ref AppBucket

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${Client}, ${Project}, ${Environment}"

  AppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig: 
        Origins:
        - DomainName: !Sub ${AppBucket}.s3.amazonaws.com
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        Enabled: 'true'
        Comment: !Sub "CloudFront distribution for ${AppBucket}"
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 5
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultRootObject: index.html
        Aliases:
        - !Ref AppUrl
        - !Ref BaseUrl
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: 'true'
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: !Ref DefaultTTL
          MaxTTL: !Ref MaxTTL
          MinTTL: !Ref MinTTL
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertArn
          SslSupportMethod: sni-only
      Tags: 
        - Key: Name
          Value: !Sub ${AWS::StackName}-distro
        - Key: Client
          Value: !Ref Client
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  WebAppDns:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${BaseUrl}.
      Comment: IP4 & IP6 alias targeted to CloudFront Distribution.
      RecordSets:
      - Name: !Ref AppUrl
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt 
            - AppDistribution
            - DomainName
      - Name: !Ref AppUrl
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt 
            - AppDistribution
            - DomainName
      - Name: !Ref BaseUrl
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt 
            - AppDistribution
            - DomainName
      - Name: !Ref BaseUrl
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt 
            - AppDistribution
            - DomainName

#End Web App Section

Outputs:
  AppBucket:
    Description: Where the angular app was deployed to
    Value: !Ref AppBucket
  WebsiteURL:
    Value: !GetAtt 
      - AppBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  CloudFrontURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - AppDistribution
          - DomainName
    Description: URL for website CDN